# -*- coding: utf-8 -*-
"""CSB Assignment 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zfT3yHYzgtebEilZh0uXOSmH2faL1zO
"""

!pip install selenium
!apt install chromium-chromedriver
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import bs4
from bs4 import BeautifulSoup
import ssl
import time

def getTableData(table):
    columns=[]
    table_rows=table.find_all("tr")
    for i in table_rows:
        closing_price=i.find_all("td")[0].get_text()
        date=i.find_all("th")[0].get_text()
        columns.append([closing_price, date])
    return columns

def main():
    wd = webdriver.Chrome('chromedriver', options=chrome_options)
    driver =webdriver.Chrome('chromedriver', options=chrome_options)
    driver.get("https://www.nasdaq.com/market-activity/stocks/aapl/historical")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);var lenOfPage=document.body.scrollHeight;return lenOfPage;")
    time.sleep(3)
    page = bs4.BeautifulSoup(driver.page_source, 'lxml')
    stats_table=page.find("tbody")
    data=getTableData(stats_table)
    print("Closing Price \t Dates")
    for i in data:
        print(" \t".join(map(str,i)))

#if __name__ == "__main__":
#    main()

main()