# -*- coding: utf-8 -*-
"""NFL Assignement 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h5YZRGhFhHiL76QG-9OeDIPZDQrRodRg
"""

import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl

def getRowData(table_row, tag):
    rowList=[]
    needed_rows=[1,2,3]
    columns=table_row.find_all(tag)
    col = [columns[i] for i in needed_rows] 
    for i in col:
        rowList.append(i.get_text())
    return rowList

def getTableData(table):
    columns=[]
    table_rows=table.find_all("tr")[1:] 
    for i in range(len(table_rows)):
        columns.append(getRowData(table_rows[i],"td"))
    return columns

def main():
    p_context = ssl.create_default_context()
    p_context.check_hostname = False
    p_context.verify_mode = ssl.CERT_NONE

    url="http://www.footballlocks.com/nfl_point_spreads.shtml"
    web_page = urllib.request.urlopen(url, context=p_context).read()
    page=BeautifulSoup(web_page,"html.parser")
    stats_table=page.find("table",{"cols":"4"})
    data=getTableData(stats_table)
    print("Favorite \t  Spread \t The Underdog")
    for i in data:
        print(" \t".join(map(str,i)))

if __name__ == "__main__":
    main()