# -*- coding: utf-8 -*-
"""Stockdata Assignment 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tlyiiEVJJSfXUNlMTDFyFO7Dexow14Sd
"""

import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl
def getRowData(table_row, tag):
    rowList=[]
    needed_rows=[0,1,2,6]
    columns=table_row.find_all(tag)
    col = (columns[i] for i in needed_rows) 
    for i in col:
        rowList.append(i.get_text())
    return rowList

def getTableData(table):
    columns=[]
    table_rows=table.find_all("tr")
    for i in range(3,23):
        columns.append(getRowData(table_rows[i],"td"))
    return columns

def main():
    p_context = ssl.create_default_context()
    p_context.check_hostname = False
    p_context.verify_mode = ssl.CERT_NONE
    url="https://www.cbssports.com/nfl/stats/playersort/nfl/year-2019-season-regular-category-touchdowns"
    web_page = urllib.request.urlopen(url, context=p_context).read()
    page=BeautifulSoup(web_page,"html.parser")
    stats_table=page.find("table")
    data=getTableData(stats_table)
    print("Player \t Position \t Team \t Total TD")
    for i in data:
        print(" \t".join(map(str,i)))

if __name__ == "__main__":
    main()